server {
    # Mendengarkan trafik HTTP di Port 80

    # GANTI INI DENGAN DOMAIN KAMU
    server_name domainmu;

    # Logging (Biar gampang debug kalau error)
    access_log /var/log/nginx/app_access.log;
    error_log /var/log/nginx/app_error.log;

    location / {
        # Arahkan ke Docker Container (Port 8000)
        proxy_pass http://localhost:8000;

        # Header Wajib (Supaya aplikasi tahu IP asli pengunjung & Cloudflare)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Penting buat Cloudflare: Memberitahu app protokol apa yang dipakai (HTTP/HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}